# -*- coding: utf-8 -*-
"""Copy of PRODIGY_GA_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bg1Mn4JeygqeMSoIauwPb07h2ZLNCPIt

# 🎨 Image Generation with Pre-trained Models
### Internship Task-02: Creating images from text prompts using Stable Diffusion
"""

!pip install diffusers transformers accelerate torch torchvision --quiet
!pip install gradio --quiet
!pip install --upgrade huggingface_hub --quiet

import torch
import matplotlib.pyplot as plt
from diffusers import StableDiffusionPipeline
from huggingface_hub import notebook_login
notebook_login()

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Using device: {device}')

pipe = StableDiffusionPipeline.from_pretrained(
    'runwayml/stable-diffusion-v1-5',
    torch_dtype=torch.float16 if device == 'cuda' else torch.float32,
    use_safetensors=True
).to(device)

if device == 'cuda':
    pipe.enable_attention_slicing()

print('✅ Stable Diffusion loaded!')

prompts = [
    'A futuristic cityscape at sunset with flying cars',
    'A magical forest with glowing mushrooms and fairies'
]

images = []
for prompt in prompts:
    img = pipe(prompt, num_inference_steps=50, guidance_scale=7.5).images[0]
    images.append((prompt, img))

for prompt, img in images:
    plt.figure(figsize=(6, 6))
    plt.imshow(img)
    plt.axis('off')
    plt.title(prompt)
    plt.show()

"""## ✅ Notebook Complete
**Instructions:**
1. Run all cells one by one.
2. Authorize with your Hugging Face token when prompted.
3. Modify prompts in the list to generate different fantasy images.
4. Download or screenshot results for your internship report.
"""